create table if not exists public.pepe_data (
    id bigint generated by default as identity primary key,
    symbol text not null default 'PEPEUSDT',
    best_bid_price numeric(30, 18) not null,
    best_bid_quantity numeric(30, 18) not null,
    best_ask_price numeric(30, 18) not null,
    best_ask_quantity numeric(30, 18) not null,
    observed_at timestamptz not null,
    created_at timestamptz not null default now()
);

create index if not exists pepe_data_observed_at_idx
    on public.pepe_data (observed_at desc);

alter table public.pepe_data enable row level security;